export const alger1 = require("./Images/alger1.jpg")
export const alger2 = require("./Images/alger2.jpg")
export const casbah1 = require("./Images/casbah1.jpg")
export const casbah2 = require("./Images/casbah2.jpg")
export const casbah3 = require("./Images/casbah3.jpg")
export const casbah4 = require("./Images/casbah4.jpg")
export const casbah5 = require("./Images/casbah5.jpg")
export const pont1 = require("./Images/pont1.jpg")
export const academie = require("./Images/academie.jpg")
export const bastille = require("./Images/Bastille.jpg")
export const demandeMariage = require("./Images/demande-mariage.jpg")
export const entreCopines =  require("./Images/entre-copines.jpg")
export const fleursSous = require("./Images/fleurs-sous.jpg")
export const grandOrsay = require("./Images/grand-orsay.jpg")
export const orsay_de_loin = require("./Images/orsay_de_loin.jpg")
export const juleVer = require("./Images/jule-ver.jpg")
export const notreDame = require("./Images/notre-dame.jpg")
export const pecheur = require("./Images/pecheur.jpg")
export const peniche = require("./Images/peniche.jpg")
export const plateau = require("./Images/plateau.jpg")
export const plateau2 = require("./Images/plateau2.jpg")
export const pontNapoleon = require("./Images/pont-napoleon.jpg")
export const pontsAmours = require("./Images/ponts-amours.jpg")
export const promeneur = require("./Images/promeneur.jpg")
export const saintLouis1 = require("./Images/saint-louis1.jpg")
export const saintLouis2 = require("./Images/Saint-Louis.jpg")
export const solitaire = require("./Images/solitaire.jpg")
export const neige = require("./Images/neige.jpg")
export const vieux_pont = require("./Images/vieux_pont.jpg")
export const avenue_fleurs = require("./Images/avenue_fleurs.jpg")


export const elyes1 = require("./Images/elyes1.jpg")
export const elyes2 = require("./Images/elyes2.jpg")
export const elyes3 = require("./Images/elyes3.jpg")
export const elyes4 = require("./Images/elyes4.jpg")

export const artist1 = require("./Images/artist1.jpg")
export const artist2 = require("./Images/artist2.jpg")
export const artelyesLogo = require("./Images/artelyes_logo.png")
export const underline = require("./Images/underline.png")
export const top = require("./Images/top.png")

